feat: add missing `proposer` field to `SafeMultisigTransactionWithTransfersResponse`
safe-global/safe-core-sdk pull request #622
Opened 2023-11-27 21:30 UTC by pradel

## What it solves

The `proposer` field is missing from the typescript definition but returned by the Safe API.

## How this PR fixes it

Add the missing field in the type.

2023-11-27 22:20 UTC, pradel commented
I have read the CLA Document and I hereby sign the CLA

2023-11-28 16:57 UTC, dasanra approved these changes

2023-11-28 16:58 UTC, dasanra requested changes
Could you please remove the question mark after `proposer`?

The parameter should always be returned from the latest Transaction Service version

2023-11-28 17:48 UTC, pradel commented
@dasanra updated

2023-11-29 09:44 UTC, dasanra approved these changes

2023-11-29 09:45 UTC, merged